name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Essencial para o jgitver

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with jgitver
        run: |
          # Executa o jgitver primeiro
          mvn jgitver:jgitver
          
          # Mostra a versão calculada
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Calculated version: $VERSION"
          
          # Build completo
          mvn -B clean verify

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: mvn -B deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}